package scanner;

import java.util.LinkedHashMap;
import java.util.Map;

public final class ModSignatures {
    private ModSignatures() {
    }

    public static final String[] PATTERNS = {
        "AimAssist", "AnchorTweaks", "AutoAnchor", "AutoCrystal", "AutoDoubleHand", "JDWP.VirtualMachine.AllModules",
        "AutoHitCrystal", "AutoPot", "AutoTotem", "AutoArmor", "InventoryTotem",
        "LegitTotem", "PingSpoof", "SelfDestruct",
        "ShieldBreaker", "TriggerBot", "AxeSpam", "WebMacro",
        "FastPlace", "WalskyOptimizer", "WalksyOptimizer", "walsky.optimizer",
        "WalksyCrystalOptimizerMod", "Donut", "Replace Mod",
        "ShieldDisabler", "SilentAim", "Totem Hit", "Wtap", "FakeLag", "dev.virel", "orchard",
        "BlockESP", "dev.krypton", "dev/krypton", "skid.krypton", "skid/krypton", "AntiMissClick",
        "LagReach", "PopSwitch", "SprintReset", "ChestSteal", "AntiBot",
        "ElytraSwap", "FastXP", "FastExp", "Refill", "AirAnchor",
        "jnativehook", "FakeInv", "HoverTotem", "AutoClicker", "AutoFirework",
        "PackSpoof", "Antiknockback", "catlean",
        "AuthBypass", "Asteria", "Prestige", "AutoEat", "AutoMine",
        "MaceSwap", "Macro198", "StunSlam", "SafeAnchor", "DoubleAnchor", "AutoTPA", "BaseFinder", "Xenon", "gypsy",
        "AutoPotRefill", "KeyPearl", "AutoNethPot", "AutoDtap",
        "AutoWeb", "AnchorAction",
        "org.chainlibs.module.impl.modules.Crystal.Y",
        "org.chainlibs.module.impl.modules.Crystal.bF",
        "org.chainlibs.module.impl.modules.Crystal.bM",
        "org.chainlibs.module.impl.modules.Crystal.bY",
        "org.chainlibs.module.impl.modules.Crystal.bq",
        "org.chainlibs.module.impl.modules.Crystal.cv",
        "org.chainlibs.module.impl.modules.Crystal.o",
        "org.chainlibs.module.impl.modules.Blatant.I",
        "org.chainlibs.module.impl.modules.Blatant.bR",
        "org.chainlibs.module.impl.modules.Blatant.bx",
        "org.chainlibs.module.impl.modules.Blatant.cj",
        "org.chainlibs.module.impl.modules.Blatant.dk",
        "imgui.gl3", "imgui.glfw",
        "BowAim", "Criticals", "Fakenick", "FakeItem",
        "invsee", "ItemExploit", "Hellion", "hellion",
        "LicenseCheckMixin", "ClientPlayerInteractionManagerAccessor",
        "ClientPlayerEntityMixim", "dev.gambleclient", "obfuscatedAuth",
        "phantom-refmap.json", "xyz.greaj",
        "じ.class", "ふ.class", "ぶ.class", "ぷ.class", "た.class",
        "ね.class", "そ.class", "な.class", "ど.class", "ぐ.class",
        "ず.class", "で.class", "つ.class", "べ.class", "せ.class",
        "と.class", "み.class", "び.class", "す.class", "の.class"
    };

    public static final String[] STRINGS = {
        "AutoCrystal", "autocrystal", "auto crystal", "cw crystal", "JDWP.VirtualMachine.AllModules",
        "dontPlaceCrystal", "dontBreakCrystal", "dev.virel", "orchard",
        "AutoHitCrystal", "autohitcrystal", "canPlaceCrystalServer", "healPotSlot",
        "ＡｕｔｏＣｒｙｓｔａｌ", "Ａｕｔｏ Ｃｒｙｓｔａｌ",
        "ＡｕｔｏＨｉｔＣｒｙｓｔａｌ",
        "AutoAnchor", "autoanchor", "auto anchor", "DoubleAnchor",
        "HasAnchor", "anchortweaks", "anchor macro", "safe anchor", "safeanchor",
        "SafeAnchor", "AirAnchor",
        "ＡｕｔｏＡｎｃｈｏｒ", "Ａｕｔｏ Ａｎｃｈｏｒ",
        "ＤｏｕｂｌｅＡｎｃｈｏｒ", "Ｄｏｕｂｌｅ Ａｎｃｈｏｒ",
        "ＳａｆｅＡｎｃｈｏｒ", "Ｓａｆｅ Ａｎｃｈｏｒ",
        "Ａｎｃｈｏｒ Ｍａｃｒｏ", "anchorMacro",
        "AutoTotem", "autototem", "auto totem", "InventoryTotem",
        "inventorytotem", "HoverTotem", "hover totem", "legittotem",
        "ＡｕｔｏＴｏｔｅｍ", "Ａｕｔｏ Ｔｏｔｅｍ",
        "ＨｏｖｅｒＴｏｔｅｍ", "Ｈｏｖｅｒ Ｔｏｔｅｍ",
        "ＩｎｖｅｎｔｏｒｙＴｏｔｅｍ", "Ａｕｔｏ Ｉｎｖｅｎｔｏｒｙ Ｔｏｔｅｍ",
        "Ａｕｔｏ Ｔｏｔｅｍ Ｈｉｔ",
        "AutoPot", "autopot", "auto pot", "speedPotSlot", "strengthPotSlot",
        "AutoArmor", "autoarmor", "auto armor",
        "ＡｕｔｏＰｏｔ", "Ａｕｔｏ Ｐｏｔ",
        "Ａｕｔｏ Ｐｏｔ Ｒｅｆｉｌｌ", "AutoPotRefill",
        "ＡｕｔｏＡｒｍｏｒ", "Ａｕｔｏ Ａｒｍｏｒ",
        "preventSwordBlockBreaking", "preventSwordBlockAttack",
        "ShieldDisabler", "ShieldBreaker",
        "ＳｈｉｅｌｄＤｉｓａｂｌｅｒ", "Ｓｈｉｅｌｄ Ｄｉｓａｂｌｅｒ",
        "Breaking shield with axe...",
        "AutoDoubleHand", "autodoublehand", "auto double hand",
        "ＡｕｔｏＤｏｕｂｌｅＨａｎｄ", "Ａｕｔｏ Ｄｏｕｂｌｅ Ｈａｎｄ",
        "AutoClicker",
        "ＡｕｔｏＣｌｉｃｋｅｒ",
        "Failed to switch to mace after axe!",
        "AutoMace", "MaceSwap", "SpearSwap",
        "ＡｕｔｏＭａｃｅ", "Ａｕｔｏ Ｍａｃｅ",
        "ＭａｃｅＳｗａｐ", "Ｍａｃｅ Ｓｗａｐ",
        "Ｓｐｅａｒ Ｓｗａｐ", "Ａｕｔｏｍａｔｉｃａｌｌｙ ａｘｅ ａｎｄ ｍａｃｅ ｓｈｉｅｌｄｅｄ ｐｌａｙｅｒｓ",
        "Ｓｔｕｎ Ｓｌａｍ", "StunSlam",
        "Donut", "JumpReset", "axespam", "axe spam",
        "findKnockbackSword", "attackRegisteredThisClick",
        "AimAssist", "aimassist", "aim assist",
        "triggerbot", "trigger bot",
        "ＡｉｍＡｓｓｉｓｔ", "Ａｉｍ Ａｓｓｉｓｔ",
        "ＴｒｉｇｇｅｒＢｏｔ", "Ｔｒｉｇｇｅｒ Ｂｏｔ",
        "Silent Rotations", "SilentRotations",
        "Ｓｉｌｅｎｔ Ｒｏｔａｔｉｏｎｓ",
        "FakeInv", "swapBackToOriginalSlot",
        "FakeLag", "pingspoof", "ping spoof",
        "ＦａｋｅＬａｇ", "Ｆａｋｅ Ｌａｇ",
        "fakePunch", "Fake Punch",
        "Ｆａｋｅ Ｐｕｎｃｈ",
        "mace_swap", "quick_strike", "macro_198", "stun_slam",
        "safe_anchor", "double_anchor", "auto_pot_refill",
        "walksy_optimizer", "key_pearl", "aim_assist",
        "auto_neth_pot", "auto_dtap", "trigger_bot", "auto_web",
        "DOUBLE_ESCAPE", "DOUBLE_RIGHTCLICK_FIRST", "DOUBLE_RIGHTCLICK_SECOND",
        "POST_CYCLE_DELAY", "PLACE_OBI", "WAIT_OBI", "PLACE_CRYSTAL", "BREAK_CRYSTAL",
        "ROTATING_DOWN", "ROTATING_BACK", "REFILLING", "PLANTING", "BONEMEALING",
        "AnchorAction", "Places two anchors for massive damage",
        "REOFFHAND_TOTEM",
        "webmacro", "web macro",
        "AntiWeb", "AutoWeb",
        "Ａｎｔｉ Ｗｅｂ", "ＡｕｔｏＷｅｂ",
        "Ｐｌａｃｅｓ Ｗｅｂｓ Ｏｎ Ｅｎｅｍｉｅｓ",
        "lvstrng", "dqrkis", "selfdestruct", "self destruct",
        "WalksyCrystalOptimizerMod", "WalksyOptimizer", "WalskyOptimizer",
        "Ｗａｌｋｓｙ Ｏｐｔｉｍｉｚｅｒ",
        "autoCrystalPlaceClock",
        "AutoFirework", "ElytraSwap", "FastXP", "FastExp", "NoJumpDelay",
        "ＥｌｙｔｒａＳｗａｐ", "Ｅｌｙｔｒａ Ｓｗａｐ",
        "PackSpoof", "Antiknockback", "catlean",
        "AuthBypass", "obfuscatedAuth", "LicenseCheckMixin",
        "BaseFinder", "invsee", "ItemExploit",
        "FreezePlayer",
        "Ｆｒｅｅｃａｍ", "Ｍｏｖｅ ｆｒｅｅｌｙ ｔｈｒｏｕｇｈ ｗａｌｌｓ",
        "Ｎｏ Ｃｌｉｐ", "Ｆｒｅｅｚｅ Ｐｌａｙｅｒ",
        "LWFH Crystal", "JDWP.VirtualMachine.AllModules",
        "ＬＷＦＨ Ｃｒｙｓｔａｌ",
        "KeyPearl", "LootYeeter",
        "ＫｅｙＰｅａｒｌ", "Ｋｅｙ Ｐｅａｒｌ",
        "Ｌｏｏｔ Ｙｅｅｔｅｒ",
        "FastPlace",
        "Ｆａｓｔ Ｐｌａｃｅ", "Ｐｌａｃｅ ｂｌｏｃｋｓ ｆａｓｔｅｒ",
        "AutoBreach",
        "Ａｕｔｏ Ｂｒｅａｃｈ",
        "setBlockBreakingCooldown", "getBlockBreakingCooldown", "blockBreakingCooldown",
        "onBlockBreaking", "setItemUseCooldown",
        "invokeDoAttack", "invokeDoItemUse", "invokeOnMouseButton",
        "onPushOutOfBlocks", "onIsGlowing",
        "Automatically switches to sword when hitting with totem",
        "arrayOfString", "POT_CHEATS",
        "Dqrkis Client", "Entity.isGlowing",
        "Activate Key", "Ａｃｔｉｖａｔｅ Ｋｅｙ",
        "Click Simulation", "Ｃｌｉｃｋ Ｓｉｍｕｌａｔｉｏｎ",
        "On RMB", "Ｏｎ ＲＭＢ",
        "No Count Glitch", "Ｎｏ Ｃｏｕｎｔ Ｇｌｉｔｃｈ",
        "No Bounce", "NoBounce", "Ｎｏ Ｂｏｕｎｃｅ", "ＮｏＢｏｕｎｃｅ",
        "Ｒｅｍｏｖｅｓ ｔｈｅ ｃｒｙｓｔａｌ ｂｏｕｎｃｅ ａｎｉｍａｔｉｏｎ",
        "Place Delay", "Ｐｌａｃｅ Ｄｅｌａｙ",
        "Break Delay", "Ｂｒｅａｋ Ｄｅｌａｙ",
        "Ｆａｓｔ Ｍｏｄｅ",
        "Place Chance", "Ｐｌａｃｅ Ｃｈａｎｃｅ",
        "Break Chance", "Ｂｒｅａｋ Ｃｈａｎｃｅ",
        "Stop On Kill", "Ｓｔｏｐ Ｏｎ Ｋｉｌｌ",
        "Ｄａｍａｇｅ Ｔｉｃｋ", "damagetick",
        "Anti Weakness", "Ａｎｔｉ Ｗｅａｋｎｅｓｓ",
        "Particle Chance", "Ｐａｒｔｉｃｌｅ Ｃｈａｎｃｅ",
        "Trigger Key", "Ｔｒｉｇｇｅｒ Ｋｅｙ",
        "Switch Delay", "Ｓｗｉｔｃｈ Ｄｅｌａｙ",
        "Totem Slot", "Ｔｏｔｅｍ Ｓｌｏｔ",
        "Silent Rotations", "Ｓｉｌｅｎｔ Ｒｏｔａｔｉｏｎｓ",
        "Smooth Rotations", "Ｓｍｏｏｔｈ Ｒｏｔａｔｉｏｎｓ",
        "Rotation Speed", "Ｒｏｔａｔｉｏｎ Ｓｐｅｅｄ",
        "Use Easing", "Ｕｓｅ Ｅａｓｉｎｇ",
        "Easing Strength", "Ｅａｓｉｎｇ Ｓｔｒｅｎｇｔｈ",
        "While Use", "Ｗｈｉｌｅ Ｕｓｅ",
        "Stop on Kill", "Ｓｔｏｐ ｏｎ Ｋｉｌｌ",
        "Click Simulation", "Ｃｌｉｃｋ Ｓｉｍｕｌａｔｉｏｎ",
        "Glowstone Delay", "Ｇｌｏｗｓｔｏｎｅ Ｄｅｌａｙ",
        "Glowstone Chance", "Ｇｌｏｗｓｔｏｎｅ Ｃｈａｎｃｅ",
        "Explode Delay", "Ｅｘｐｌｏｄｅ Ｄｅｌａｙ",
        "Explode Chance", "Ｅｘｐｌｏｄｅ Ｃｈａｎｃｅ",
        "Explode Slot", "Ｅｘｐｌｏｄｅ Ｓｌｏｔ",
        "Only Charge", "Ｏｎｌｙ Ｃｈａｒｇｅ",
        "Anchor Macro", "Ａｎｃｈｏｒ Ｍａｃｒｏ",
        "Reach Distance", "Ｒｅａｃｈ Ｄｉｓｔａｎｃｅ",
        "Min Height", "Ｍｉｎ Ｈｅｉｇｈｔ",
        "Min Fall Speed", "Ｍｉｎ Ｆａｌｌ Ｓｐｅｅｄ",
        "Attack Delay", "Ａｔｔａｃｋ Ｄｅｌａｙ",
        "Breach Delay", "Ｂｒｅａｃｈ Ｄｅｌａｙ",
        "Require Elytra", "Ｒｅｑｕｉｒｅ Ｅｌｙｔｒａ",
        "Auto Switch Back", "Ａｕｔｏ Ｓｗｉｔｃｈ Ｂａｃｋ",
        "Check Line of Sight", "Ｃｈｅｃｋ Ｌｉｎｅ ｏｆ Ｓｉｇｈｔ",
        "Only When Falling", "Ｏｎｌｙ Ｗｈｅｎ Ｆａｌｌｉｎｇ",
        "Require Crit", "Ｒｅｑｕｉｒｅ Ｃｒｉｔ",
        "Show Status Display", "Ｓｈｏｗ Ｓｔａｔｕｓ Ｄｉｓｐｌａｙ",
        "Stop On Crystal", "Ｓｔｏｐ Ｏｎ Ｃｒｙｓｔａｌ",
        "Check Shield", "Ｃｈｅｃｋ Ｓｈｉｅｌｄ",
        "On Pop", "Ｏｎ Ｐｏｐ",
        "Predict Damage", "Ｐｒｅｄｉｃｔ Ｄａｍａｇｅ",
        "On Ground", "Ｏｎ Ｇｒｏｕｎｄ",
        "Check Players", "Ｃｈｅｃｋ Ｐｌａｙｅｒｓ",
        "Predict Crystals", "Ｐｒｅｄｉｃｔ Ｃｒｙｓｔａｌｓ",
        "Check Aim", "Ｃｈｅｃｋ Ａｉｍ",
        "Check Items", "Ｃｈｅｃｋ Ｉｔｅｍｓ",
        "Activates Above", "Ａｃｔｉｖａｔｅｓ Ａｂｏｖｅ",
        "Blatant", "Ｂｌａｔａｎｔ",
        "Force Totem", "Ｆｏｒｃｅ Ｔｏｔｅｍ",
        "Stay Open For", "Ｓｔａｙ Ｏｐｅｎ Ｆｏｒ",
        "Auto Inventory Totem", "Ａｕｔｏ Ｉｎｖｅｎｔｏｒｙ Ｔｏｔｅｍ",
        "Only On Pop", "Ｏｎｌｙ Ｏｎ Ｐｏｐ",
        "Vertical Speed", "Ｖｅｒｔｉｃａｌ Ｓｐｅｅｄ",
        "Hover Totem", "Ｈｏｖｅｒ Ｔｏｔｅｍ",
        "Swap Speed", "Ｓｗａｐ Ｓｐｅｅｄ",
        "Strict One-Tick", "Ｓｔｒｉｃｔ Ｏｎｅ－Ｔｉｃｋ",
        "Mace Priority", "Ｍａｃｅ Ｐｒｉｏｒｉｔｙ",
        "Min Totems", "Ｍｉｎ Ｔｏｔｅｍｓ",
        "Min Pearls", "Ｍｉｎ Ｐｅａｒｌｓ",
        "Totem First", "Ｔｏｔｅｍ Ｆｉｒｓｔ",
        "Drop Interval", "Ｄｒｏｐ Ｉｎｔｅｒｖａｌ",
        "Random Pattern", "Ｒａｎｄｏｍ Ｐａｔｔｅｒｎ",
        "Loot Yeeter", "Ｌｏｏｔ Ｙｅｅｔｅｒ",
        "Horizontal Aim Speed", "Ｈｏｒｉｚｏｎｔａｌ Ａｉｍ Ｓｐｅｅｄ",
        "Vertical Aim Speed", "Ｖｅｒｔｉｃａｌ Ａｉｍ Ｓｐｅｅｄ",
        "Include Head", "Ｉｎｃｌｕｄｅ Ｈｅａｄ",
        "Web Delay", "Ｗｅｂ Ｄｅｌａｙ",
        "Holding Web", "Ｈｏｌｄｉｎｇ Ｗｅｂ",
        "Not When Affects Player", "Ｎｏｔ Ｗｈｅｎ Ａｆｆｅｃｔｓ Ｐｌａｙｅｒ",
        "Hit Delay", "Ｈｉｔ Ｄｅｌａｙ",
        "Ｓｗｉｔｃｈ Ｂａｃｋ",
        "Require Hold Axe", "Ｒｅｑｕｉｒｅ Ｈｏｌｄ Ａｘｅ",
        "Fake Punch", "Ｆａｋｅ Ｐｕｎｃｈ",
        "placeInterval", "breakInterval", "stopOnKill",
        "activateOnRightClick", "holdCrystal",
        "ｐｌａｃｅＩｎｔｅｒｖａｌ", "ｂｒｅａｋＩｎｔｅｒｖａｌ",
        "ｓｔｏｐＯｎＫｉｌｌ", "ａｃｔｉｖａｔｅＯｎＲｉｇｈｔＣｌｉｃｋ",
        "ｄａｍａｇｅｔｉｃｋ", "ｈｏｌｄＣｒｙｓｔａｌ",
        "ｆａｋｅＰｕｎｃｈ",
        "Ｒｅｆｉｌｌｓ ｙｏｕｒ ｈｏｔｂａｒ ｗｉｔｈ ｐｏｔｉｏｎｓ",
        "Ｋｅｐｓ ｙｏｕ ｓｐｒｉｎｔｉｎｇ ａｔ ａｌｌ ｔｉｍｅｓ",
        "Ｐｌａｃｅｓ ａｎｃｈｏｒ， ｃｈａｒｇｅｓ ｉｔ， ｐｒｏｔｅｃｔｓ ｙｏｕ， ａｎｄ ｅｘｐｌｏｄｅｓ",
        "Ａｕｔｏ ｓｗａｐ ｔｏ ｓｐｅａｒ ｏｎ ａｔｔａｃｋ",
        "Macro Key", "Ａｕｔｏ Ｐｏｔ", "Ｍａｃｒｏ Ｋｅｙ",
        "KillAura", "ClickAura", "MultiAura", "ForceField", "LegitAura",
        "AimBot", "AutoAim", "SilentAim", "AimLock", "HeadSnap",
        "CrystalAura",
        "AnchorAura", "AnchorFill", "AnchorPlace",
        "BedAura", "AutoBed", "BedBomb", "BedPlace",
        "BowAimbot", "BowSpam", "AutoBow",
        "AutoCrit", "CritBypass", "AlwaysCrit", "CriticalHit",
        "ReachHack", "ExtendReach", "LongReach", "HitboxExpand",
        "AntiKB", "NoKnockback", "GrimVelocity", "GrimDisabler", "VelocitySpoof", "KBReduce",
        "OffhandTotem", "TotemSwitch",
        "AutoWeapon", "AutoSword", "AutoCity", "Burrow", "SelfTrap",
        "HoleFiller", "AntiSurround", "AntiBurrow",
        "WTap", "TargetStrafe", "AutoGap", "AutoPearl",
        "FlyHack", "CreativeFlight", "BoatFly", "PacketFly", "AirJump",
        "SpeedHack", "BHop", "BunnyHop",
        "AntiFall", "NoFallDamage", "SafeFall",
        "StepHack", "FastClimb", "AutoStep", "HighStep",
        "WaterWalk", "LiquidWalk", "LavaWalk",
        "NoSlow", "NoSlowdown", "NoWeb", "NoSoulSand",
        "WallHack",
        "ElytraSpeed", "InstantElytra",
        "ScaffoldWalk", "FastBridge", "BuildHelper", "AutoBridge",
        "Nuker", "NukerLegit", "InstantBreak",
        "GhostHand", "NoSwing",
        "PlaceAssist", "AirPlace", "AutoPlace", "InstantPlace",
        "PlayerESP", "MobESP", "ItemESP", "StorageESP", "ChestESP",
        "Tracers", "NameTagsHack",
        "XRayHack", "OreFinder", "CaveFinder", "OreESP",
        "NewChunks", "ChunkBorders", "TunnelFinder",
        "TargetHUD", "ReachDisplay",
        "DoubleClicker", "JitterClick", "ButterflyClick", "CPSBoost",
        "ChestStealer", "InvManager", "InvMovebypass",
        "AutoSprint", "AntiAFK", "AutoRespawn",
        "PopSwitch",
        "FakeLatency", "FakePing", "SpoofRotation", "PositionSpoof",
        "GameSpeed", "SpeedTimer",
        "GrimBypass", "VulcanBypass", "MatrixBypass",
        "AACBypass", "VerusDisabler", "IntaveBypass", "WatchdogBypass",
        "PacketMine", "PacketWalk", "PacketSneak", "PacketCancel", "PacketDupe", "PacketSpam",
        "SelfDestruct", "HideClient",
        "SessionStealer", "TokenLogger", "TokenGrabber", "DiscordToken",
        "RemoteAccess", "ReverseShell", "C2Server", "Backdoor", "KeyLogger",
        "StashFinder", "TrailFinder",
        "imgui.binding",
        "JNativeHook", "GlobalScreen", "NativeKeyListener",
        "client-refmap.json", "cheat-refmap.json",
        "aHR0cDovL2FwaS5ub3ZhY2xpZW50LmxvbC93ZWJob29rLnR4dA==",
        "meteordevelopment", "cc/novoline",
        "com/alan/clients", "club/maxstats", "wtf/moonlight",
        "me/zeroeightsix/kami", "net/ccbluex", "today/opai",
        "net/minecraft/injection", "org/chainlibs/module/impl/modules",
        "xyz/greaj", "com/cheatbreaker", "com/moonsworth",
        "doomsdayclient", "DoomsdayClient", "doomsday.jar",
        "novaclient", "api.novaclient.lol",
        "WalksyOptimizer", "LWFH Crystal",
        "vape.gg", "vapeclient", "VapeClient", "VapeLite",
        "intent.store", "IntentClient",
        "rise.today", "riseclient.com",
        "meteor-client", "meteorclient", "meteordevelopment.meteorclient",
        "liquidbounce", "fdp-client", "net.ccbluex",
        "novoware", "novoclient",
        "aristois", "impactclient", "azura",
        "pandaware", "skilled", "moonClient", "astolfo",
        "futureClient", "konas", "rusherhack", "inertia", "exhibition",
        "dev.krypton", "dev/krypton", "skid.krypton", "skid/krypton",
        "VirginClient", "virgin client",
        "catlean", "CatleanClient", "catlean client",
        "ArgonClient", "argon client",
        "Asteria", "AsteriaClient", "asteria client",
        "Prestige", "PrestigeClient", "prestige client", "prestigeclient.vip",
        "gypsy", "GypsyClient", "gypsy client",
        "Xenon", "XenonClient", "xenon client",
        "GrimClient", "grim client",
        "phantom-refmap.json",
        "dqrkis.xyz", "Dqrkis Client"
    };

    public static final Map<String, String[]> OBFUSCATORS = new LinkedHashMap<>();

    public static final String[] LEGIT_MOD_IDS = {
        "vmp-fabric", "vmp", "lithium", "sodium", "iris", "fabric-api",
        "modmenu", "ferrite-core", "lazydfu", "starlight", "entityculling",
        "memoryleakfix", "krypton", "c2me-fabric", "smoothboot-fabric",
        "immediatelyfast", "noisium", "threadtweak"
    };

    public static final String[] MAVEN_PREFIXES = {
        "com_", "org_", "net_", "io_", "dev_", "gs_", "xyz_",
        "app_", "me_", "tv_", "uk_", "be_", "fr_", "de_"
    };

    public static final String[] WHITELISTED_SLUGS = {
        "viafabricplus", "viafabricversion"
    };

    static {
        OBFUSCATORS.put("Skidfuscator", new String[]{"dev/skidfuscator", "Skidfuscator", "skidfuscator.dev"});
        OBFUSCATORS.put("Paramorphism", new String[]{"Paramorphism", "paramorphism-", "dev/paramorphism"});
        OBFUSCATORS.put("Radon", new String[]{"ItzSomebody/Radon", "me/itzsomebody/radon", "Radon Obfuscator"});
        OBFUSCATORS.put("Caesium", new String[]{"sim0n/Caesium", "Caesium Obfuscator", "dev/sim0n/caesium"});
        OBFUSCATORS.put("Bozar", new String[]{"vimasig/Bozar", "Bozar Obfuscator", "com/bozar"});
        OBFUSCATORS.put("Branchlock", new String[]{"Branchlock", "branchlock.dev"});
        OBFUSCATORS.put("Binscure", new String[]{"Binscure", "com/binscure"});
        OBFUSCATORS.put("SuperBlaubeere", new String[]{"superblaubeere", "superblaubeere27"});
        OBFUSCATORS.put("Qprotect", new String[]{"Qprotect", "QProtect", "mdma.dev/qprotect"});
        OBFUSCATORS.put("Zelix", new String[]{"ZKMFLOW", "ZKM", "ZelixKlassMaster", "com/zelix"});
        OBFUSCATORS.put("Stringer", new String[]{"StringerJavaObfuscator", "com/licel/stringer"});
        OBFUSCATORS.put("JNIC", new String[]{"JNIC", "jnic.obf", "jnic-obfuscator"});
        OBFUSCATORS.put("Scuti", new String[]{"ScutiObf", "scuti.obf"});
        OBFUSCATORS.put("Smoke", new String[]{"SmokeObf", "smoke.obf"});
    }
}
